services:
  ingestor:
    image: ghcr.io/antndev/data-injector:latest
    container_name: ingestor
    restart: unless-stopped
    expose:
      - "8000"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/data
      - ./db:/db
      - openwebui_openwebui_data:/openwebui-data # important!
    networks:
      - proxy
      - openwebui_rag-internal

networks:
  proxy:
    external: true
  openwebui_rag-internal:
    external: true

volumes:
  openwebui_openwebui_data:
    external: true
